#!/bin/bash

#-Saudação-#

echo '########################'
echo '||Configurando o Linux||'
echo '########################'

#-Indicador de progresso-#



#-Variáveis-#

URL_GOOGLE_CHROME="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
DIRETORIO_DOWNLOADS="$HOME/Downloads/programas"
#URL_WINE_KEY="https://dl.winehq.org/wine-builds/winehq.key"
#URL_PPA_WINE="https://dl.winehq.org/wine-builds/ubuntu/"
#PPA_LIBRATBAG="ppa:libratbag-piper/piper-libratbag-git"
#PPA_LUTRIS="ppa:lutris-team/lutris"
#PPA_GRAPHICS_DRIVERS="ppa:graphics-drivers/ppa"
PROGRAMAS_PARA_INSTALAR=(snapd virtualbox)

#-Requisitos-#

### Remover travas do apt ##
sudo rm /var/lib/dpkg/lock-frontend
sudo rm /var/cache/apt/archives/lock
sudo dpgk --configure -a

### Adicionando/Confirmando arquitetura de 32 bits ##
sudo dpkg --add-architecture i386

### Atualizando o repositório ##
sudo apt update -y

### Adicionando repositórios de terceiros e suporte a Snap (Driver Logitech, Lutris e Drivers Nvidia)##

#sudo apt-add-repository "$PPA_LIBRATBAG" -y
#sudo add-apt-repository "$PPA_LUTRIS" -y
#sudo apt-add-repository "$PPA_GRAPHICS_DRIVERS" -y
#wget -nc "$URL_WINE_KEY"
#sudo apt-key add winehq.key
#sudo apt-add-repository "deb $URL_PPA_WINE bionic main"

#-Execução-#

### Atualizando o repositório depois da adição de novos repositórios ##
sudo apt update -y

### Download e instalaçao de programas externos ##
mkdir "$DIRETORIO_DOWNLOADS"
wget -c "$URL_GOOGLE_CHROME"       -P "$DIRETORIO_DOWNLOADS"

### Instalando pacotes .deb baixados na sessão anterior ##
sudo dpkg -i $DIRETORIO_DOWNLOADS/*.deb
